<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tablets</name>
   <tag></tag>
   <elementGuidId>4cfcda18-7a2a-4d1e-bbce-fbc31ffcdf03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menu']/div[2]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62b91d93-590c-4420-8ca9-e5a7f51a9e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/index.php?route=product/category&amp;path=57</value>
      <webElementGuid>906c96d1-e558-41bf-878e-858cf87d5ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tablets</value>
      <webElementGuid>70e0a2af-a230-4ec4-bbd2-243c9925346b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;collapse navbar-collapse navbar-ex1-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[4]/a[1]</value>
      <webElementGuid>9de1a32d-7a99-4483-9b5a-945cbfe1753a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menu']/div[2]/ul/li[4]/a</value>
      <webElementGuid>1c883895-1e8e-4693-a17f-5cfbbf3495a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tablets')]</value>
      <webElementGuid>6e6b908b-9780-4e96-9e0a-abb9dd4e1605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Components'])[1]/following::a[1]</value>
      <webElementGuid>f6df2da2-b8f0-4447-ad1c-6fabfe86c790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Cameras (0)'])[1]/following::a[2]</value>
      <webElementGuid>5cb91f7b-67b0-40fd-80b1-c05350c55128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software'])[1]/preceding::a[1]</value>
      <webElementGuid>3d13ab06-e7b4-49b3-9369-a68281bff8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phones &amp; PDAs'])[1]/preceding::a[2]</value>
      <webElementGuid>c7b2ae98-a997-495a-a1b5-ba502ecdd6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tablets']/parent::*</value>
      <webElementGuid>3b8fead7-4ece-4f81-9f5f-8b31f72047ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://opencart.abstracta.us:80/index.php?route=product/category&amp;path=57']</value>
      <webElementGuid>e1ca9806-c59b-4095-9694-a8f6c72c8f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/ul/li[4]/a</value>
      <webElementGuid>d15439a6-aec8-4278-a38b-23c7f31adf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://opencart.abstracta.us:80/index.php?route=product/category&amp;path=57' and (text() = 'Tablets' or . = 'Tablets')]</value>
      <webElementGuid>d511cb88-e63b-4a37-95c9-4d4c1045a378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
