<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card_nameOnCard</name>
   <tag></tag>
   <elementGuidId>015e1be0-1741-464c-a0ab-fc0a277e48be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameOnCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nameOnCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b74bc58-1427-4f21-ba0c-769564d625d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42941808-76ab-4605-8573-b3c2ee925d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>0fc27378-8cfe-432f-8e85-aa983244b8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Smith</value>
      <webElementGuid>24f3937f-c598-4513-bbb7-60423ff3a6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>b6f3f953-bbd6-46c2-91a2-c1be1e0af217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameOnCard&quot;)</value>
      <webElementGuid>f4471060-b141-46fa-927f-14c23ceac4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameOnCard']</value>
      <webElementGuid>0701f86c-536b-47ac-bd19-35a22255cfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c1b09a46-cadf-40bb-a599-d1ef6485d89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameOnCard' and @placeholder = 'John Smith' and @name = 'nameOnCard']</value>
      <webElementGuid>dd09751d-4eab-4e61-8469-074176ca2b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
